version: "3.8"

services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: pookiey-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=6969
      - NODE_ENV=production
    ports:
      - "6969:6969"


